version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=note
      - DB_USER=root
      - DB_PASS=your_mysql_password
    volumes:
      - .:/app
      - /app/node_modules

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: note
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
